global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'arkana-api'
    static_configs:
      - targets: ['arkana-api:8000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth:8000']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
